name: heart_crystal
description: ë§ˆìŒì„ ê¸°ë¡í•˜ëŠ” ê°ì„± ìˆ˜ì • ì•± ðŸ’œ
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  firebase_ui_auth: ^1.7.0
  firebase_ui_oauth_google: ^1.3.0

  # Core ê¸°ëŠ¥
  path_provider: ^2.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.20.2
  uuid: ^3.0.7
  csv: ^5.0.0
  easy_pie_chart: ^1.0.2

  # UI/ë””ìžì¸
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.68.0
  google_sign_in_web: ^0.12.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/crystal.png
